<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('subcategorias', function (Blueprint $table) {
            $table->id();
            $table->string('nombre', 64);
            $table->foreignId('categoria_id')->constrained('categorias', 'id')->cascadeOnDelete();
        });

        $subcategorias = [
            ['id' => 1, 'nombre' => 'otro', 'categoria_id' => 2],
            ['id' => 2, 'nombre' => 'postre o helado', 'categoria_id' => 2],
            ['id' => 3, 'nombre' => 'fruta o verdura fresca', 'categoria_id' => 2],
            ['id' => 4, 'nombre' => 'carne o huevos', 'categoria_id' => 2],
            ['id' => 5, 'nombre' => 'especias o aditivos', 'categoria_id' => 2],
            ['id' => 6, 'nombre' => 'almuerzo o desayuno', 'categoria_id' => 2],
            ['id' => 7, 'nombre' => 'chatarra preparada', 'categoria_id' => 2],
            ['id' => 8, 'nombre' => 'chatarra industrial', 'categoria_id' => 2],
            ['id' => 9, 'nombre' => 'pan o pastel', 'categoria_id' => 2],
            ['id' => 10, 'nombre' => 'bebidas', 'categoria_id' => 2],
            ['id' => 21, 'nombre' => 'otro', 'categoria_id' => 5],
            ['id' => 22, 'nombre' => 'cuidado de la piel', 'categoria_id' => 5],
            ['id' => 23, 'nombre' => 'cuidado del pelo', 'categoria_id' => 5],
            ['id' => 24, 'nombre' => 'labial', 'categoria_id' => 5],
            ['id' => 25, 'nombre' => 'sombra', 'categoria_id' => 5],
            ['id' => 26, 'nombre' => 'delineador', 'categoria_id' => 5],
            ['id' => 27, 'nombre' => 'piercing', 'categoria_id' => 5],
            ['id' => 28, 'nombre' => 'tatuaje', 'categoria_id' => 5],
            ['id' => 29, 'nombre' => 'maniquiur', 'categoria_id' => 5],
            ['id' => 30, 'nombre' => 'peluqueria', 'categoria_id' => 5],
            ['id' => 31, 'nombre' => 'otro', 'categoria_id' => 6],
            ['id' => 32, 'nombre' => 'balón', 'categoria_id' => 6],
            ['id' => 33, 'nombre' => 'pesas', 'categoria_id' => 6],
            ['id' => 34, 'nombre' => 'suplemento alimenticio', 'categoria_id' => 6],
            ['id' => 35, 'nombre' => 'patineta o patines', 'categoria_id' => 6],
            ['id' => 36, 'nombre' => 'implementos acuaticos', 'categoria_id' => 6],
            ['id' => 37, 'nombre' => 'implementos terrestres', 'categoria_id' => 6],
            ['id' => 38, 'nombre' => 'implementos extremos', 'categoria_id' => 6],
            ['id' => 39, 'nombre' => 'arte marcial o lucha', 'categoria_id' => 6],
            ['id' => 40, 'nombre' => 'aseo deportivo', 'categoria_id' => 6],
            ['id' => 41, 'nombre' => 'otro', 'categoria_id' => 7],
            ['id' => 42, 'nombre' => 'computador de escritorio', 'categoria_id' => 7],
            ['id' => 43, 'nombre' => 'computador portátil', 'categoria_id' => 7],
            ['id' => 44, 'nombre' => 'periféricos para computador', 'categoria_id' => 7],
            ['id' => 45, 'nombre' => 'celular', 'categoria_id' => 7],
            ['id' => 46, 'nombre' => 'cámara fotográfica', 'categoria_id' => 7],
            ['id' => 47, 'nombre' => 'calculadora o mediciónes', 'categoria_id' => 7],
            ['id' => 48, 'nombre' => 'tableta para arte', 'categoria_id' => 7],
            ['id' => 49, 'nombre' => 'audifónos, reloj o corporales', 'categoria_id' => 7],
            ['id' => 50, 'nombre' => 'sistema de seguridad', 'categoria_id' => 7],
            ['id' => 51, 'nombre' => 'otro', 'categoria_id' => 4],
            ['id' => 52, 'nombre' => 'taladro, pulidora o similar', 'categoria_id' => 4],
            ['id' => 53, 'nombre' => 'martillo, alicate o similar', 'categoria_id' => 4],
            ['id' => 54, 'nombre' => 'licuadora, microondas o similar', 'categoria_id' => 4],
            ['id' => 55, 'nombre' => 'seguridad para ajustar bicicleta', 'categoria_id' => 4],
            ['id' => 56, 'nombre' => 'escuadra o regla para dibujo', 'categoria_id' => 4],
            ['id' => 57, 'nombre' => 'metro o medidores', 'categoria_id' => 4],
            ['id' => 58, 'nombre' => 'tijera, visturí o similar', 'categoria_id' => 4],
            ['id' => 59, 'nombre' => 'ventilador o aire acondicionado', 'categoria_id' => 4],
            ['id' => 60, 'nombre' => 'kit de mecánico', 'categoria_id' => 4],
            ['id' => 61, 'nombre' => 'otro', 'categoria_id' => 4],
            ['id' => 62, 'nombre' => 'taladro, pulidora o similar', 'categoria_id' => 4],
            ['id' => 63, 'nombre' => 'martillo, alicate o similar', 'categoria_id' => 4],
            ['id' => 64, 'nombre' => 'licuadora, microondas o similar', 'categoria_id' => 4],
            ['id' => 65, 'nombre' => 'seguridad para ajustar bicicleta', 'categoria_id' => 4],
            ['id' => 66, 'nombre' => 'escuadra o regla para dibujo', 'categoria_id' => 4],
            ['id' => 67, 'nombre' => 'metro o medidores', 'categoria_id' => 4],
            ['id' => 68, 'nombre' => 'tijera, visturí o similar', 'categoria_id' => 4],
            ['id' => 69, 'nombre' => 'ventilador o aire acondicionado', 'categoria_id' => 4],
            ['id' => 70, 'nombre' => 'kit de mecánico', 'categoria_id' => 4],
            ['id' => 71, 'nombre' => 'otro', 'categoria_id' => 12],
            ['id' => 72, 'nombre' => 'perro', 'categoria_id' => 12],
            ['id' => 73, 'nombre' => 'gato', 'categoria_id' => 12],
            ['id' => 74, 'nombre' => 'pez', 'categoria_id' => 12],
            ['id' => 75, 'nombre' => 'alimento', 'categoria_id' => 12],
            ['id' => 76, 'nombre' => 'correa', 'categoria_id' => 12],
            ['id' => 77, 'nombre' => 'juguete', 'categoria_id' => 12],
            ['id' => 78, 'nombre' => 'roedor', 'categoria_id' => 12],
            ['id' => 79, 'nombre' => 'tapete', 'categoria_id' => 12],
            ['id' => 80, 'nombre' => 'ropa', 'categoria_id' => 12],
            ['id' => 81, 'nombre' => 'otro', 'categoria_id' => 10],
            ['id' => 82, 'nombre' => 'silla regulable', 'categoria_id' => 10],
            ['id' => 83, 'nombre' => 'silla estática', 'categoria_id' => 10],
            ['id' => 84, 'nombre' => 'sillón grande', 'categoria_id' => 10],
            ['id' => 85, 'nombre' => 'mesa', 'categoria_id' => 10],
            ['id' => 86, 'nombre' => 'cama o colchón', 'categoria_id' => 10],
            ['id' => 87, 'nombre' => 'matera', 'categoria_id' => 10],
            ['id' => 88, 'nombre' => 'armario o nochero', 'categoria_id' => 10],
            ['id' => 89, 'nombre' => 'escritorio', 'categoria_id' => 10],
            ['id' => 90, 'nombre' => 'tapete', 'categoria_id' => 10],
            ['id' => 91, 'nombre' => 'otro', 'categoria_id' => 13],
            ['id' => 92, 'nombre' => 'otro', 'categoria_id' => 3],
            ['id' => 93, 'nombre' => 'cartónes o cajas', 'categoria_id' => 3],
            ['id' => 94, 'nombre' => 'telas y costura', 'categoria_id' => 3],
            ['id' => 95, 'nombre' => 'pegamentos', 'categoria_id' => 3],
            ['id' => 96, 'nombre' => 'cuadernos, carpetas', 'categoria_id' => 3],
            ['id' => 97, 'nombre' => 'colores, pinturas, pinceles', 'categoria_id' => 3],
            ['id' => 98, 'nombre' => 'libros', 'categoria_id' => 3],
            ['id' => 99, 'nombre' => 'lápices, marcadores, lapiceros', 'categoria_id' => 3],
            ['id' => 100, 'nombre' => 'borradores, sacapuntas', 'categoria_id' => 3],
            ['id' => 101, 'nombre' => 'papel, fomi, cartulina', 'categoria_id' => 3],
            ['id' => 102, 'nombre' => 'otro', 'categoria_id' => 8],
            ['id' => 103, 'nombre' => 'entrenamiento deportivo', 'categoria_id' => 8],
            ['id' => 104, 'nombre' => 'eseñanza artística', 'categoria_id' => 8],
            ['id' => 105, 'nombre' => 'enseñanza tecnológica', 'categoria_id' => 8],
            ['id' => 106, 'nombre' => 'mantenimiento computadora', 'categoria_id' => 8],
            ['id' => 107, 'nombre' => 'reparación dispositivos', 'categoria_id' => 8],
            ['id' => 108, 'nombre' => 'preparación de comidas', 'categoria_id' => 8],
            ['id' => 109, 'nombre' => 'documentación', 'categoria_id' => 8],
            ['id' => 110, 'nombre' => 'creación de arte o manualidades', 'categoria_id' => 8],
            ['id' => 111, 'nombre' => 'cuidado y aseo', 'categoria_id' => 8],
            ['id' => 112, 'nombre' => 'otro', 'categoria_id' => 9],
            ['id' => 113, 'nombre' => 'juego deportivo', 'categoria_id' => 9],
            ['id' => 114, 'nombre' => 'juego videojuegos', 'categoria_id' => 9],
            ['id' => 115, 'nombre' => 'practicar idiomas', 'categoria_id' => 9],
            ['id' => 116, 'nombre' => 'fiesta y baile', 'categoria_id' => 9],
            ['id' => 117, 'nombre' => 'charlar', 'categoria_id' => 9],
            ['id' => 118, 'nombre' => 'emprendimiento', 'categoria_id' => 9],
            ['id' => 119, 'nombre' => 'paseos y viajes', 'categoria_id' => 9],
            ['id' => 120, 'nombre' => 'seguir en redes', 'categoria_id' => 9],
            ['id' => 121, 'nombre' => 'religión e ideologías', 'categoria_id' => 9],
            ['id' => 122, 'nombre' => 'otro', 'categoria_id' => 11],
            ['id' => 123, 'nombre' => 'bicicleta', 'categoria_id' => 11],
            ['id' => 124, 'nombre' => 'moto de gasolina', 'categoria_id' => 11],
            ['id' => 125, 'nombre' => 'casco de moto', 'categoria_id' => 11],
            ['id' => 126, 'nombre' => 'moto eléctrica', 'categoria_id' => 11],
            ['id' => 127, 'nombre' => 'bici o patín eléctricos', 'categoria_id' => 11],
            ['id' => 128, 'nombre' => 'carro', 'categoria_id' => 11],
            ['id' => 129, 'nombre' => 'chaleco, guantes o vestimenta', 'categoria_id' => 11],
            ['id' => 130, 'nombre' => 'repuesto', 'categoria_id' => 11],
            ['id' => 131, 'nombre' => 'parrillas o implementos', 'categoria_id' => 11],
            ['id' => 132, 'nombre' => 'otro', 'categoria_id' => 1],
            ['id' => 133, 'nombre' => 'calzado', 'categoria_id' => 1],
            ['id' => 134, 'nombre' => 'sombrero', 'categoria_id' => 1],
            ['id' => 135, 'nombre' => 'pantalón', 'categoria_id' => 1],
            ['id' => 136, 'nombre' => 'camisa', 'categoria_id' => 1],
            ['id' => 137, 'nombre' => 'vestido', 'categoria_id' => 1],
            ['id' => 138, 'nombre' => 'falda', 'categoria_id' => 1],
            ['id' => 139, 'nombre' => 'medias o guantes', 'categoria_id' => 1],
            ['id' => 140, 'nombre' => 'chaleco o buzo', 'categoria_id' => 1],
            ['id' => 141, 'nombre' => 'colgandijas', 'categoria_id' => 1],
            ['id' => 142, 'nombre' => 'colgantes', 'categoria_id' => 14],
            ['id' => 143, 'nombre' => 'figurillas', 'categoria_id' => 14],
            ['id' => 144, 'nombre' => 'materas o jardín', 'categoria_id' => 14],
            ['id' => 145, 'nombre' => 'de metal', 'categoria_id' => 14],
            ['id' => 146, 'nombre' => 'de plástico', 'categoria_id' => 14],
            ['id' => 147, 'nombre' => 'de madera', 'categoria_id' => 14],
            ['id' => 148, 'nombre' => 'de porcelana', 'categoria_id' => 14],
            ['id' => 149, 'nombre' => 'afiches o pinturas', 'categoria_id' => 14],
            ['id' => 150, 'nombre' => 'peluches', 'categoria_id' => 14],
            ['id' => 151, 'nombre' => 'otro', 'categoria_id' => 14],
        ];

        DB::table('subcategorias')->insert($subcategorias);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('subcategorias');
    }
};
